name: Update products

on:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - run: pip install -r requirements.txt

      - run: python app/parser.py
